######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 24 01:06:30 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ScnShot.h
SOURCES += ScnShot.cpp
